### PR TITLE
Openaire - now XML response based

### PR DESCRIPTION
**Pull request by chreman**
test runs

### CODE REVIEW

**Comment by pkraker** [comment]
Awesome, thanks! It works well for certain calls (see e.g. project ID 246686, 611742), but fails for others. Here are the two errors that I've seen, along with relevant project IDs. I suspect that most of them do not have enough related publications/datasets.

Project IDs: 230636
Error:
```
> input_data = get_papers(query, params)
Warning in xpath_search(x$node, x$doc, xpath = xpath, nsMap = ns, num_results = Inf) :
  Undefined namespace prefix [1219]
xmlXPathEval: evaluation failed
```

Project IDs: 911723, 8488
Error:
```
> input_data = get_papers(query, params)
Warning in xpath_search(x$node, x$doc, xpath = xpath, nsMap = ns, num_results = Inf) :
  Undefined namespace prefix [1219]
xmlXPathEval: evaluation failed
Warning in xpath_search(x$node, x$doc, xpath = xpath, nsMap = ns, num_results = Inf) :
  Undefined namespace prefix [1219]
xmlXPathEval: evaluation failed
Error in matrix(nrow = nrow(all_artifacts)) : data is too long
```

**Comment by pkraker** [comment]
I also noticed that project ID 330731 reports 67 publications with `roa_pubs`, but only 22 are reported in the visualization. Here is the relevant output from that run:

```
> input_data = get_papers(query, params)
Warning in xpath_search(x$node, x$doc, xpath = xpath, nsMap = ns, num_results = Inf) :
  Undefined namespace prefix [1219]
xmlXPathEval: evaluation failed
> 
> output_json = vis_layout(input_data$text, input_data$metadata, max_clusters=MAX_CLUSTERS,
+                          add_stop_words=ADDITIONAL_STOP_WORDS, testing=TRUE, list_size=-1)
Read 574 items
[1] "calc matrix"
[1] "normalize matrix"
[1] "create clusters"
Warning in weightSMART(x, spec = "ntn") : empty document(s): 10
Minimum stress for given dimensionality:  0.2941957 
r^2 for minimum stress configuration:  0.636748 
```

**Comment by chreman** [comment]
improved error handling, so it now returns NULL and not a total crash. need to look a bit more into the specific projects to make sure it is always related to the low/zero number of results and not something else.

**Comment by pkraker** [comment]
Errors are looking much better now, thanks! The problem with project ID 330731, however, is still there (see above).

**Comment by chreman** [comment]
I can reproduce the error on my part, but currently I'd have to relay it to openaire-API.
`roa_pubs(fp7 = "330731")` indeed returns 67 publications, on the other hand `http://api.openaire.eu/search/publications?projectID=330731&funder=EC&format=xml` for the XML-format the API shows me `<total>22</total>`

**Comment by pkraker** [comment]
Thanks! So this is a bug then that we should report back to OpenAIRE. From my point of view, this can be merge. But please revert the last commit - we always report a more precise date, if we can.

**Comment by pkraker** [comment]
Excellent, merging this now!

**Pull request merged**
