### PR TITLE
Viper Frontend Metric Scaling

### PR DESCRIPTION
**Pull request by tarrow**
Scaling by some metrics

Configurable in the headstart config file.

Includes dummy explanations

Depends on some frontend and back end commits that haven't been merged yet.

### CODE REVIEW

**Comment by pkraker** [comment]
Thanks, this looks great! Worked out of the box for me when testing it with the OpenAIRE project. 

I have only a few minor comments, which all have to do with the config:

* Please move `scale_explanation` in the config to the localization (currently located in `default-config.js`). This would be a good opportunity to create an own localization for OpenAIRE (currently it's `eng_pubmed`).
* In the default mode, `content_based` should be set to true and it shouldn't be possible to sort by citations (to achieve this, simply remove it from `sort_options` in the config).
* The labels in the list, the sort options, and the papers should change depending on which metric is selected. My suggestion would be to simply use `citations`, `tweets` and `readers` for now. This can be achieved by adapting `base_unit`` and `sort_options` in the config. As for the sort_options, you may need to rename the attributes in `io.prepareData` to enable the sort functionality (e.g. `citation_count` to `citations`).

**Comment by pkraker** [comment]
Contrary to what I said above in the last bullet point, you don't need to rename the attributes to make sure the sorting works - you simply need to change `readers` in the localization to the desired label.

**Comment by pkraker** [comment]
One final comment: it should be possible to set different labels for the options in the dropdown in the localization. So for example set `citations` for `citation_count` and so on.

**Comment by tarrow** [comment]
Thanks for the comments. I'll address them with a new patch in the next few days.

**Pull request merged**
