### PR TITLE
checking for missing methods and default values per localizations,

### PR DESCRIPTION
**Pull request by rbachleitner**
some fixes concerning list-only mode.

### CODE REVIEW

**Comment by pkraker** [comment]
Looks good, but there is one issue with these changes: it's not possible to remove metrics using the flag `content_based` any more. You can test this using `search_doaj.html` in the `search_repos` example.

**Comment by rbachleitner** [comment]
@pkraker Can you check again? I think it was just one wrong conditional

**Comment by pkraker** [comment]
Sorry, this was actually working before the requested change. Can I ask you to revert the last change?

**Comment by rbachleitner** [comment]
@pkraker Should be like before again.

**Pull request merged**
