### PR TITLE
issue #131 - move publicPath to separate config file

### PR DESCRIPTION
**Pull request by jaels**
People will need to change also the path to the config file from the webpack file - remove example

### CODE REVIEW

**Comment by tarrow** [comment]
I might have missed something but won't this simply mean we get people now accidentally submitting patches that look like?

```
-const config = require('./config.example.js');
+const config = require('./config.js');
```

**Comment by pkraker** [comment]
Looks really good, but I agree with both comments by @tarrow. 

It should be:
```
const config = require('./config.js');
```

Also, please add this step to the documentation here: Readme.md#getting-started

**Comment by jaels** [comment]
Hope it's good now.
Let me know...

**Comment by pkraker** [comment]
Looking good, thanks! I have two small last change requests: 

1. Please change the path in `config.example.js` to `http://localhost:8080/dist/`. This way, it will work out of the box for people running the webpack server once they have copied and renamed the example file.

1. Please change README.md from
```
Open a new file named `config.js` in the main `Headstart` folder, looking like `config.example.js`, and change the publicPath to the path of the dist directory.

Dev: specify a full path including protocol (it's usually the same path specified in the example).
Production: specify full path excluding protocol e.g. `//openknowledgemaps.org/headstart/dist`

Now you can run a local dev server: 
 	npm start
```

to 

```
Duplicate the file `config.example.js` in the root folder and rename it to `config.js`. 

Now you can run a local dev server: 
 	npm start

To run Headstart on a different server (e.g. Apache), you need to set the publicPath in `config.js` to the URL of the `dist` directory:
* Dev: specify the full path including protocol, e.g. `http://localhost/headstart/dist`
* Production: specify the full path excluding protocol, e.g. `//example.org/headstart/dist`
```

**Comment by jaels** [comment]
Done.

**Comment by pkraker** [comment]
Awesome! Merging now :+1:

**Pull request merged**
