### PR TITLE
update headstart js packages to webpack 3

### LINKED ISSUE #362: npm run dev doesn't run because of CleanWebpackPlugin
CleanWebpackPlugin version > 2.0.0 is not compatible with our current configuration, but is currently installed autmatically when doing `npm install`.
A workaround for now would be to apply the following diff:
```
-    "clean-webpack-plugin": "*",
+    "clean-webpack-plugin": "< 2.0.0",
```
but this should be solved more comprehensively together with #352.

### PR DESCRIPTION
**Pull request by rbachleitner**
Second try - this should be a more comprehensive update of our javascript dependencies. I have confirmed on two machines that `npm install`and `npm run dev/prod/start` runs through.

It was necessary to change the webpack config since there have been some changes from version 1 to version 3. A quick test of the local_files example was also carried out and confirmed.

This still leaves us with 4 vulnerabilites (according to `npm audit`) and those reside within jquery and its plugins. I want to update jquery in a second step, since updating jquery from major version 2 to major version 3 will necessitate changes within the application code due to api changes (or the use of a plugin such as jquery migrate).

Of course a third step would be to migrate from webpack version 3 to webpack version 4 if we should need the newest features that webpack 4 offers.

fixes #362

### CODE REVIEW

**Comment by chreman** [comment]
Thank you! After removing the node_modules folder and doing a clean `npm install`, I can confirm that `npm run dev/prod/start` works with node 6.12.3 (which was my current version at the time), and local deployment and testing of frontend interactivity on maps did not show any difference. During deployment I've noticed following things:
`
├─┬ UNMET PEER DEPENDENCY webpack@3.12.0
│ ├── acorn@5.7.3 
│ ├─┬ acorn-dynamic-import@2.0.2 
`
This error was not reported after I switched to node 8.16.0 or 10.16.0, however. We should take note of this requirement in our setup documentation.

Also thanks for having a look at the remaining vulnerabilities, I agree that this should be handled in a separate issue due to the API changes.

**Comment by pkraker** [comment]
Thanks! Both upgrade and fresh install with node 6.13.1 using `npm install/dev/prod` worked for me. However, when running the local_files example, I got an error when attempting to switch between files (dropdown on top) and the switch did not occur. The error is:

```
uncaught exception: event tofile inappropriate in current state none
```
In addition, I was not able to run `npm start`, which produced the following error:
```
> headstart@1.0.0 start C:\Users\pkraker\xampp\htdocs\headstart_fresh
> webpack-dev-server -d --progress

Configuration file found but no entry configured.
Use --help to display the CLI options.
npm ERR! code ELIFECYCLE
npm ERR! errno 4294967295
npm ERR! headstart@1.0.0 start: `webpack-dev-server -d --progress`
npm ERR! Exit status 4294967295
npm ERR!
npm ERR! Failed at the headstart@1.0.0 start script.
```

Please address these two errors. Both of them do not occur on the current master with @rbachleitner's hotfix of setting `clean-webpack-plugin` to <2.0.0.

In addition, as @chreman, I received warnings during `npm install`. For me, they were:
```
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read https://babeljs.io/env to update!
npm WARN deprecated hoek@5.0.4: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated extract-text-webpack-plugin@3.0.2: Deprecated. Please use https://github.com/webpack-contrib/mini-css-extract-plugin
npm WARN prefer global node-gyp@3.8.0 should be installed with -g
npm WARN mini-css-extract-plugin@0.3.0 requires a peer of webpack@^4.3.0 but none was installed.
npm WARN css-loader@2.1.1 requires a peer of webpack@^4.0.0 but none was installed.
```
After switching to the latest stable node version (12.4.0) with npm 6.9.0, `npm install`. Therefore, I am optimistic that we can drop the requirement for node 6 once the issues above are addressed.

**Comment by chreman** [comment]
I can reproduce this error as well, in my case I suspect it is related to an old local version of webpack.config.js, which holds local config and was not updated to the new format automatically, maybe this applies to your case too?

**Comment by pkraker** [comment]
I tested this on a freshly checked out copy, where the error occurred as well. So it’s not due to a modified version of the webpack config.

**Comment by rbachleitner** [comment]
Thanks for testing and comments, I will look into the unresolved issues this week.

**Comment by pkraker** [comment]
@rbachleitner I tested it with npm 3.10.10 on Windows and MacOS.

**Comment by chreman** [comment]
@rbachleitner any updates on that issue? With the commit `npm install/run dev/run prod` work fine, but `npm start` still gives following error
```
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! headstart@1.0.0 start: `webpack-dev-server -d --progress`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the headstart@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
Also, when deploying the frontend, the interactive map remains blank and debugging it in Firefox shows following error in the console:
```
ReferenceError: data_config is not defined headstart.js line 1 > eval:20:7
    start app.js:12
```
where eval:20:7 is this
`  if (data_config) Object.assign(__WEBPACK_IMPORTED_MODULE_0_config__["a" /* default */], data_config);`
and refers to L12 in `app.js`. I hope these information help!

**Comment by chreman** [comment]
Obsolete after #390

**Pull request closed without merging**
