### PR TITLE
Core fields

### PR DESCRIPTION
**Pull request by chreman**
* please note that with this commit the CORE API key is expected to be set as an Renviron variable as detailed [here](https://github.com/ropensci/rcoreoa)
* switched search behaviour to core_advanced search to enable queries as requested in #263 (search by year) - fine grained date search and other parameters are still pending
* added url, oa_state and link as requested in #265 
  * oa_state is not given in CORE metadata and defaults to 2 (unknown)
  * url and link currently follow heuristics

`published_in` may be tricky, there is only `publisher` in the metadata which looks like
```
[51] "Institute for Apprenticeships"                                      "Institute for Apprenticeships"                                     
[53] "Institute for Apprenticeships"                                      "International Council for Open and Distance Education (ICDE)" 
```
or `journals` which looks like
```
[[90]]
  title               identifiers
1    NA 2013-9144, issn:2013-9144

[[91]]
  title               identifiers
1    NA 2297-198x, issn:2297-198X
```
I'm not sure these are the journals we are looking for.

### CODE REVIEW

**Comment by pkraker** [comment]
Thanks! Have you checked that the Renviron approach does work with the system call from PHP? For me, it works in RStudio but not when I call it from the frontend.

As we do need `oa_state` in the frontend to determine when to display the PDF link, my suggestion would be to use the PDF link as a workaround (i.e., if it exists, oa_state is set to 1, otherwise to 2).

For `pulished_in` the journals field looks like the best candidate. Can you check, if name is always N/A, and if it is, flag this to the CORE people?

**Comment by chreman** [comment]
Yes, I have checked the Renviron approach. Depending on which user calls R, you may have to set it for either user, root, or Renviron.site.

I added a heuristic for the oa_state as described, and a heuristic for the published_in field, which defaults to `""` if no information is available, takes the journal title if not NA, or the identifier if present. In the test case it looks like
```
[81] ""                          ""                          ""                          ""                          "2307-3187, issn:2307-3187"
[86] "2304-070x, issn:2304-070X" "issn:1825-7321, 1825-7321" ""                          ""                          ""                         
[91] ""                          ""                          ""                          ""                          "" 
```
I will contact CORE to get more info.

**Comment by pkraker** [comment]
Thanks, adding the key to Renviron.site did the trick. This works now as expected - the only thing that needs changing is that `published_in` should not use the ISSN as a fallback as this is more likely to confuse the user than anything else.

**Comment by pkraker** [comment]
One more thing: searchCORE.php still expects a CORE API key to be set in the config.ini. This should be removed as it is not needed anymore with the environment variable approach.

**Comment by pkraker** [comment]
Looks good now, thanks!

**Pull request merged**
