### PR TITLE
Clusternaming

### PR DESCRIPTION
**Pull request by chreman**
simple proposal for #140:
exclude terms that appear less often than _lower bound_ from going into the keyword TermDocumentMatrix. initial tests indicate that a small value of 2 (excluding any keywords that only appear once) already improves labels with our small corpus sizes. a value of 3 in some cases already leads to bubbles where a possible slot remains unfilled because there are no candidates with freq >= 3.

### CODE REVIEW

**Comment by pkraker** [comment]
I am not sure that I am seeing any difference at the moment. For example in the map on climate change prevention (BASE), there is a cluster with first label "Obesity prevention" that only contains one paper on the topic.

**Comment by chreman** [comment]
the minimum threshold (as it is implemented now) looks at the frequency of keyword candidates in general. so if like in this case, "obesity prevention" occurs more than twice e.g. in the abstract, it is still considered valid.
excluding keywords that only have one source paper is another good way to better represent cluster content. I'll have a look at that.

**Comment by pkraker** [comment]
Thanks for the clarification! Yes, I think that the latter approach would be more promising. Otherwise, it just takes one paper to repeat a phrase over and over again to take over the labels in a bubble.

**Comment by chreman** [comment]
I added a global min_doc bound of 2. a quick test then showed, that cluster naming became simplistic after that, so I then changed back the _local_ bound to 1.
Now hopefully the influence of a single document is reduced, while still showing the diversity of topics overall.

**Comment by pkraker** [comment]
Thanks, now I can definitely see a difference. One question: when testing it with philosophy in BASE (which may be one of the most extreme edge cases that we have), I noticed that there were a few bubbles with just 1 paper that still had labels. How does that work? My assumption was that the global bound means that the term would have to appear at least in 2 papers in the same cluster.

**Comment by chreman** [comment]
Global indeed means global (as far as I understand the documentation of TermDocumentMatrix in R), so a term needs to appear at least in two papers of the whole corpus, not only within one cluster (the bound is applied as a control in the creation of the tfidf-matrix from the clustered corpus). In your described case we're unintendendly lucky, or else clusters with one paper would be without title.

**Comment by pkraker** [comment]
Thanks for the clarification. That's why many of the labels did already become very generic in my test cases (see e.g. the one on climate change prevention). Also given the potential problem of unnamed clusters, I suggest the following solution:

For each cluster, a label must appear in at least n documents within the cluster, where n is dependent on the number of documents in the bubble. My initial idea for n would be n=1 for 1-3 documents, n=2 for 4-8 documents and n=3 for more than 8 documents.

**Comment by chreman** [comment]
```
                                                     Docs
Terms                                                 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26
  adaptation                                          0 0 0 0 0 0 0 0 0  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0
  _adaptation                                         0 0 0 0 0 0 0 0 0  0  1  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0
  _adaptation_measures                                0 0 0 1 0 0 0 0 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  _aflatoxin                                          0 0 0 0 0 0 0 0 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0  0
  _analytic_network_process                           0 0 0 0 0 0 0 0 0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0
  _and_utilization                                    0 0 0 0 0 0 0 0 0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0
  aspergillus                                         0 0 0 0 0 0 0 0 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0  0
  _average_temperature                                0 0 0 0 0 0 0 0 0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0  0  0
  _biocontrol                                         0 0 0 0 0 0 0 0 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0  0
  _b_journal                                          1 0 0 0 0 0 0 0 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  breaks                                              0 0 0 0 0 0 0 0 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0
  _business                                           0 1 0 0 0 0 0 0 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  _cats                                               0 0 0 0 0 0 0 0 0  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0
  _change_in_values_and_in_attitude                   0 0 0 0 0 0 0 0 0  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0
  _chemical_technology                                0 0 0 0 0 0 0 0 0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  _climate_change                                     0 1 0 0 0 0 0 0 0  0  0  0  0  1  0  0  1  1  0  0  0  1  0  1  0  0
  climate_change                                      1 0 1 1 0 1 1 0 0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  1
  _climate_financing                                  0 0 0 0 0 0 0 0 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1
  _climate_policy                                     0 0 0 0 0 0 0 0 0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  _climate_responsive                                 0 0 0 0 0 0 0 0 0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0
  _climates                                           0 0 0 0 0 0 0 0 0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0
  climatic_change                                     0 0 0 0 0 0 0 0 0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0
  _climatic_changes                                   0 0 0 0 0 0 0 0 0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0
  climatic_changes                                    0 0 0 0 0 0 0 0 1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  _climatic_changes--government_policy                0 0 0 0 0 0 0 0 0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0
  __climatology                                       0 0 0 0 0 1 0 0 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  _communication                                      1 0 0 0 0 0 0 0 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  community                                           0 0 0 0 0 0 0 0 0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  _congenital_toxoplasmosis                           0 0 0 0 0 0 0 0 0  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0
  __consumption                                       0 0 0 0 0 0 0 0 0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0
  _costa-rica                                         0 0 0 0 0 0 0 0 0  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0
  _cost-benefit_analysis                              0 0 0 0 0 1 0 0 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  _cycle_of_climate_change_prevention                 0 1 0 0 0 0 0 0 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  decades                                             0 0 0 0 1 0 0 0 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  disaster                                            0 0 0 0 0 0 0 0 0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  _drinking-water                                     0 0 0 0 0 0 0 0 0  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0
  _drought                                            0 0 0 0 0 0 0 0 0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0
  _drought_indices                                    0 0 0 0 0 0 0 0 0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0
 [ getOption("max.print") est atteint -- 96 lignes omises ]
<<TermDocumentMatrix (terms: 10, documents: 26)>>
Non-/sparse entries: 29/231
Sparsity           : 89%
Maximal term length: 24
Weighting          : term frequency (tf)

                          Docs
Terms                      1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26
  _adaptation              0 0 0 0 0 0 0 0 0  0  1  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0
  _climate_change          0 1 0 0 0 0 0 0 0  0  0  0  0  1  0  0  1  1  0  0  0  1  0  1  0  0
  climate_change           1 0 1 1 0 1 1 0 0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  1
  _hungary                 0 0 0 0 0 0 0 0 0  0  0  1  0  0  0  0  0  0  0  0  0  0  1  0  0  0
  __leisure                0 0 0 0 0 0 0 0 0  0  0  0  0  0  0  0  0  1  0  0  0  0  1  0  0  0
  _prevention              1 0 0 0 0 1 0 0 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  __science                0 0 0 0 0 1 0 0 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0  0
  _sustainable_development 0 1 0 0 0 0 0 0 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1
  __technology             0 0 0 0 0 0 1 0 0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  _urban_sociology         0 0 0 0 0 0 0 0 0  0  0  0  0  0  0  0  0  1  0  0  0  0  1  0  0  0
<<TermDocumentMatrix (terms: 72, documents: 17)>>
Non-/sparse entries: 78/1146
Sparsity           : 94%
Maximal term length: 38
Weighting          : term frequency (tf)
```
```
                                        Docs
Terms                                    1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17
  _ยุทธศาสตร์                              0 0 0 0 0 0 0 0 0  0  0  1  0  0  0  0  0
  _การเปลี่ยนแปลงสภาพ_ภูมิอากาศ              0 0 0 0 0 0 0 0 0  0  0  1  0  0  0  0  0
  _การกัดเซาะชายฝั่งทะเล                    0 0 0 0 0 0 0 0 0  0  0  1  0  0  0  0  0
  ผู้นำ                                    0 0 0 0 0 0 0 0 0  0  0  1  0  0  0  0  0
  adult                                  0 0 0 1 0 0 0 0 0  0  0  0  0  0  0  0  0
  _agriculture                           0 0 0 1 0 0 0 0 0  0  0  0  0  0  0  0  0
  areas                                  0 0 0 0 0 0 0 0 0  1  0  0  0  0  0  0  0
  assessment_prevention                  0 0 0 0 0 0 0 0 0  1  0  0  0  0  0  0  0
  _bassin_mediterraneen                  1 0 0 0 0 0 0 0 0  0  0  0  0  0  0  0  0
  _changement_climatique                 1 0 0 0 0 0 0 0 0  0  0  0  0  0  0  0  0
  _child                                 0 0 0 1 0 0 0 0 0  0  0  0  0  0  0  0  0
  _climate_change                        0 0 0 1 0 0 1 0 1  0  0  1  1  0  1  0  0
  __climatology                          0 0 0 0 0 0 0 0 1  0  0  0  0  0  0  0  0
  collective                             0 0 0 0 1 0 0 0 0  0  0  0  0  0  0  0  0
  __colonies_                            0 0 0 0 0 0 1 0 0  0  0  0  0  0  0  0  0
  dilemma                                0 0 0 0 1 0 0 0 0  0  0  0  0  0  0  0  0
  _direito                               0 0 0 0 0 0 0 0 0  0  0  0  1  0  0  0  0
  _direito_ambiental                     0 0 0 0 0 0 0 0 0  0  0  0  1  0  0  0  0
  _disasters                             0 0 0 1 0 0 0 0 0  0  0  0  0  0  0  0  0
  emergency_management                   0 0 0 0 0 0 0 0 0  0  0  0  0  0  0  0  1
  _employees--mental_health              0 0 0 0 0 0 0 1 0  0  0  0  0  0  0  0  0
  _engineering_(_                        0 0 0 0 0 0 0 0 0  0  0  0  0  0  0  1  0
  _evolution                             0 0 0 0 0 0 0 0 0  0  0  0  0  0  0  1  0
  _finland                               0 0 0 0 0 0 1 0 0  0  0  0  0  0  0  0  0
  _food_supply                           0 0 0 1 0 0 0 0 0  0  0  0  0  0  0  0  0
  habitual                               0 0 0 0 0 0 0 0 0  0  0  0  0  1  0  0  0
  hospital                               0 0 0 0 0 0 0 0 0  0  0  0  0  0  0  1  0
  households                             0 1 0 0 0 0 0 0 0  0  0  0  0  0  0  0  0
  _humans                                0 0 0 1 0 0 0 0 0  0  0  0  0  0  0  0  0
  _ice_pack                              0 0 0 0 0 0 1 0 0  0  0  0  0  0  0  0  0
  ict                                    0 0 0 0 0 0 1 0 0  0  0  0  0  0  0  0  0
  _impact_and_adaptation                 0 0 0 0 0 0 0 0 1  0  0  0  0  0  0  0  0
  incendie                               1 0 0 0 0 0 0 0 0  0  0  0  0  0  0  0  0
  _infection                             0 0 0 0 0 0 0 0 0  0  0  0  0  0  0  1  0
  intervention                           0 0 0 0 0 1 0 0 0  0  0  0  0  0  0  0  0
  job_stress                             0 0 0 0 0 0 0 1 0  0  0  0  0  0  0  0  0
  _leader                                0 0 0 0 0 0 0 0 0  0  0  1  0  0  0  0  0
  _management                            0 0 0 0 0 0 1 0 0  0  0  0  0  0  0  0  0
  message_framing                        0 0 0 0 0 0 0 0 0  0  0  0  0  0  1  0  0
  mspd                                   0 0 0 0 0 1 0 0 0  0  0  0  0  0  0  0  0
  _national_plan_water_security          0 0 0 0 0 0 0 0 0  0  0  0  1  0  0  0  0
  northwest_china                        0 0 0 0 0 0 0 0 1  0  0  0  0  0  0  0  0
  _nutritional_physiological_phenomena   0 0 0 1 0 0 0 0 0  0  0  0  0  0  0  0  0
  obesity_prevention                     0 0 0 0 0 0 0 0 0  0  1  0  0  0  0  0  0
  _persuasion                            0 0 0 0 0 0 0 0 0  0  0  0  0  0  1  0  0
  _police                                0 0 0 0 0 0 0 1 0  0  0  0  0  0  0  0  0
  political_economy                      0 0 1 0 0 0 0 0 0  0  0  0  0  0  0  0  0
  poverty                                0 1 0 0 0 0 0 0 0  0  0  0  0  0  0  0  0
  preparedness                           0 0 0 0 0 0 0 0 0  0  0  0  0  0  0  0  1
  _prevention                            0 0 0 0 0 0 1 0 0  0  0  0  0  0  0  0  0
  _prevention_des_feux_de_forets         1 0 0 0 0 0 0 0 0  0  0  0  0  0  0  0  0
  _public_consortium                     0 0 0 0 0 0 0 0 0  0  0  0  1  0  0  0  0
  _public_policy                         0 0 0 1 0 0 0 0 0  0  0  0  0  0  0  0  0
  _quality_of_work_life                  0 0 0 0 0 0 0 1 0  0  0  0  0  0  0  0  0
  regulations                            0 0 0 0 0 0 0 0 0  0  1  0  0  0  0  0  0
  _regulatory_focus                      0 0 0 0 0 0 0 0 0  0  0  0  0  0  1  0  0
  _relief_work                           0 0 0 1 0 0 0 0 0  0  0  0  0  0  0  0  0
  _risk                                  0 0 0 0 0 0 1 0 0  0  0  0  0  0  0  0  0
 [ getOption("max.print") est atteint -- 14 lignes omises ]
<<TermDocumentMatrix (terms: 2, documents: 17)>>
Non-/sparse entries: 8/26
Sparsity           : 76%
Maximal term length: 15
Weighting          : term frequency (tf)

                 Docs
Terms             1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17
  _climate_change 0 0 0 1 0 0 1 0 1  0  0  1  1  0  1  0  0
  vulnerability   0 1 0 0 0 0 0 0 0  1  0  0  0  0  0  0  0
<<TermDocumentMatrix (terms: 2, documents: 3)>>
Non-/sparse entries: 3/3
Sparsity           : 50%
Maximal term length: 20
Weighting          : term frequency (tf)
```
```
                      Docs
Terms                  1 2 3
  epidemiology         1 0 0
  malaria_transmission 0 1 1
<<TermDocumentMatrix (terms: 1, documents: 3)>>
Non-/sparse entries: 2/1
Sparsity           : 33%
Maximal term length: 20
Weighting          : term frequency (tf)

                      Docs
Terms                  1 2 3
  malaria_transmission 0 1 1
<<TermDocumentMatrix (terms: 59, documents: 8)>>
Non-/sparse entries: 61/411
Sparsity           : 87%
Maximal term length: 31
Weighting          : term frequency (tf)
```
```
                                 Docs
Terms                             1 2 3 4 5 6 7 8
  _adaptation                     1 0 0 0 0 0 0 0
  _africa                         1 0 0 0 0 0 0 0
  _agriculture                    0 0 1 0 0 0 0 0
  air_pollution                   0 0 0 1 0 0 0 0
  _allergens                      0 1 0 0 0 0 0 0
  _allergic                       0 1 0 0 0 0 0 0
  _animal_culture                 0 0 1 0 0 0 0 0
  _animal_health                  1 0 0 0 0 0 0 0
  arctic                          0 0 0 0 0 0 1 0
  _asthma                         0 1 0 0 0 0 0 0
  _atopic                         0 1 0 0 0 0 0 0
  _biogeography                   0 0 0 0 0 1 0 0
  bovine_ephemeral_fever          0 0 1 0 0 0 0 0
  _cardiovascular_disease         0 0 0 1 0 0 0 0
  __cattle                        0 0 1 0 0 0 0 0
  _climate_change                 0 0 1 1 0 0 0 1
  climate_change                  1 0 0 0 0 0 0 0
  _control_programs               1 0 0 0 0 0 0 0
  __dengue                        0 0 0 0 0 1 0 0
  _dermatitis                     0 1 0 0 0 0 0 0
  _diagnosis                      0 0 1 0 0 0 0 0
  _dynamics                       0 0 0 0 0 1 0 0
  ecological_niche_models         0 0 0 0 0 1 0 0
  _ecosystems                     0 1 0 0 0 0 0 0
  _emissions                      0 0 0 0 0 1 0 0
  environment                     0 1 0 0 0 0 0 0
  _environment                    0 1 0 0 0 0 0 0
  _environmental_health           0 1 0 0 0 0 0 0
  _environmental_impact           1 0 0 0 0 0 0 0
  _environmental_management       0 1 0 0 0 0 0 0
  _epidemiology                   0 0 1 0 0 0 0 0
  folkhälsovetenskap              0 0 0 0 1 0 0 0
  _framework                      0 0 0 0 0 1 0 0
  _gaps_in_knowledge              0 0 0 0 0 0 0 1
  _general                        0 1 0 0 0 0 0 0
  _geographic_distributions       0 0 0 0 0 1 0 0
  _global_hälsa                   0 0 0 0 1 0 0 0
  _global_warming                 1 0 0 0 0 0 0 0
  _greenhouse_effect              0 1 0 0 0 0 0 0
  infectious_diseases             0 0 0 0 0 0 1 0
  _livestock                      1 0 0 0 0 0 0 0
  _microbiology                   0 1 0 0 0 0 0 0
  _preparedness                   1 0 0 0 0 0 0 0
  _prevention_and_control         0 1 0 0 0 0 0 0
  _public_health/gesundheitswesen 0 1 0 0 0 0 0 0
  _recommendations                0 0 0 0 0 0 0 1
  _respiratory_disease            0 0 0 1 0 0 0 0
  _rhinitis                       0 1 0 0 0 0 0 0
  _seasonal                       0 1 0 0 0 0 0 0
  _socialmedicin_och_epidemiologi 0 0 0 0 1 0 0 0
  _species_distributions          0 0 0 0 0 1 0 0
  _surveillance_system            1 0 0 0 0 0 0 0
  _transmission                   0 0 0 0 0 1 0 0
  _us_arctic                      0 0 0 0 0 0 0 1
  _vector                         0 0 1 0 0 0 0 0
  _vector-borne_diseases          1 0 0 0 0 0 0 0
  __veterinary_medicine           0 0 1 0 0 0 0 0
  _water_supply                   1 0 0 0 0 0 0 0
  zoonotic_infections             0 0 0 0 0 0 0 1
<<TermDocumentMatrix (terms: 1, documents: 8)>>
Non-/sparse entries: 3/5
Sparsity           : 62%
Maximal term length: 15
Weighting          : term frequency (tf)

                 Docs
Terms             1 2 3 4 5 6 7 8
  _climate_change 0 0 1 1 0 0 0 1
<<TermDocumentMatrix (terms: 53, documents: 12)>>
Non-/sparse entries: 61/575
Sparsity           : 90%
Maximal term length: 34
Weighting          : term frequency (tf)
```
```
                                    Docs
Terms                                1 2 3 4 5 6 7 8 9 10 11 12
  adaptation                         0 0 1 0 0 0 0 0 0  0  0  1
  _adaptation                        0 1 0 0 0 0 0 0 0  0  0  0
  _air_pollution                     0 0 0 0 0 0 0 1 0  0  0  0
  _allergy                           0 0 0 0 0 0 0 1 0  0  0  0
  arctic                             0 0 0 0 0 1 0 0 0  0  0  0
  _biological_products               0 0 0 0 0 0 0 1 0  0  0  0
  _circumpolar                       0 0 0 0 0 1 0 0 0  0  0  0
  _climate_change                    0 1 1 0 0 1 0 0 0  0  1  2
  climate_change                     0 0 0 0 0 0 0 1 0  0  0  0
  _community_child_health            0 0 0 0 0 0 1 0 0  0  0  0
  community_medicine                 0 0 0 0 0 0 0 0 0  0  1  0
  _countries                         1 0 0 0 0 0 0 0 0  0  0  0
  _emissions                         1 0 0 0 0 0 0 0 0  0  0  0
  environment                        0 0 0 0 0 0 0 0 1  0  0  0
  _environment                       0 0 0 0 0 0 0 0 0  0  0  1
  _environmental_policy              0 0 0 0 0 0 0 0 0  0  0  1
  _epidemiology                      0 0 0 0 0 0 0 0 1  0  0  0
  __green_space                      1 0 0 0 0 0 0 0 0  0  0  0
  _health                            0 0 0 0 0 0 0 0 0  0  0  1
  _health_impact                     0 0 0 0 0 0 0 0 0  0  1  0
  _health_policy                     0 0 0 0 0 1 0 0 0  0  0  0
  _health_status                     0 0 0 0 0 0 0 0 0  0  0  1
  _heat-health_action_plans          0 1 0 0 0 0 0 0 0  0  0  0
  _humans                            0 0 0 0 0 0 0 0 0  0  0  1
  _infectious_disease                0 0 0 0 0 1 0 0 0  0  0  0
  local_governments                  0 1 0 0 0 0 0 0 0  0  0  0
  medical_and_health_sciences        0 0 0 0 0 0 1 0 0  0  0  0
  __medicine                         0 1 1 0 0 1 0 0 0  0  0  0
  medicine_and_health_sciences       0 0 0 0 0 0 0 0 0  1  0  0
  _mitigation                        0 0 0 0 0 0 0 0 0  0  0  1
  _models                            0 0 0 0 0 0 0 0 0  0  0  1
  _myocardial_infarction             0 0 0 0 0 0 0 0 1  0  0  0
  nepal                              0 0 0 0 1 0 0 0 0  0  0  0
  _one_health                        0 0 0 0 0 1 0 0 0  0  0  0
  pakki                              0 0 0 0 1 0 0 0 0  0  0  0
  perceived_increase                 0 0 0 0 1 0 0 0 0  0  0  0
  _policy                            0 0 0 0 0 1 0 0 0  0  0  0
  _population                        1 0 0 0 0 0 0 0 0  0  0  0
  _public_aspects_of_medicine        0 1 1 0 0 0 0 0 0  0  0  0
  public_aspects_of_medicine         0 0 0 1 0 0 0 0 0  0  0  0
  _public_health                     0 0 1 0 0 0 0 0 0  0  0  0
  _public_health_agency              0 0 1 0 0 0 0 0 0  0  0  0
  _public_health_and_health_services 0 0 0 0 0 0 1 0 0  0  0  0
  _resilience                        0 0 1 0 0 0 0 0 0  0  0  0
  _risk_factor                       0 0 0 0 0 0 0 0 1  0  0  0
  _risk_prevention                   0 0 0 0 0 0 0 0 0  0  1  0
  _socioeconomic_factors             0 0 0 0 0 0 0 0 0  0  0  1
  _statistical                       0 0 0 0 0 0 0 0 0  0  0  1
  _temperature                       1 0 0 0 0 0 0 0 0  0  0  0
  urban___excess_mortality           1 0 0 0 0 0 0 0 0  0  0  0
  _us_cities                         1 0 0 0 0 0 0 0 0  0  0  0
  _well-being                        0 0 0 0 0 0 0 0 0  0  0  1
  _worker                            0 0 0 0 0 0 0 1 0  0  0  0
<<TermDocumentMatrix (terms: 4, documents: 12)>>
Non-/sparse entries: 12/36
Sparsity           : 75%
Maximal term length: 27
Weighting          : term frequency (tf)


                             Docs
Terms                         1 2 3 4 5 6 7 8 9 10 11 12
  adaptation                  0 0 1 0 0 0 0 0 0  0  0  1
  _climate_change             0 1 1 0 0 1 0 0 0  0  1  2
  __medicine                  0 1 1 0 0 1 0 0 0  0  0  0
  _public_aspects_of_medicine 0 1 1 0 0 0 0 0 0  0  0  0
<<TermDocumentMatrix (terms: 25, documents: 4)>>
Non-/sparse entries: 33/67
Sparsity           : 67%
Maximal term length: 31
Weighting          : term frequency (tf)
```
```
                                 Docs
Terms                             1 2 3 4
  _adult                          0 1 0 0
  _capacity_building              1 0 0 0
  _challenges                     0 0 1 1
  _china                          0 1 0 0
  _climate_change                 0 1 0 0
  climate_change                  1 0 1 1
  _communicable_diseases          0 1 0 0
  _disease_control_and_prevention 0 0 1 1
  _disease_surveillance           0 0 1 1
  _epidemiological_monitoring     0 1 0 0
  _female                         0 1 0 0
  _government_agencies            0 1 0 0
  _health_personnel               0 1 0 0
  humans                          0 1 0 0
  _imported_cases                 1 0 0 0
  _infectious_disease             0 0 1 1
  _infectious_diseases            1 0 0 0
  _malaria                        1 0 0 0
  _male                           0 1 0 0
  __medicine                      0 0 0 1
  _middle_aged                    0 1 0 0
  _perception                     1 1 0 0
  _public_aspects_of_medicine     0 0 0 1
  _urbanization                   0 0 1 1
  _young_adult                    0 1 0 0
<<TermDocumentMatrix (terms: 7, documents: 4)>>
Non-/sparse entries: 15/13
Sparsity           : 46%
Maximal term length: 31
Weighting          : term frequency (tf)


                                 Docs
Terms                             1 2 3 4
  _challenges                     0 0 1 1
  climate_change                  1 0 1 1
  _disease_control_and_prevention 0 0 1 1
  _disease_surveillance           0 0 1 1
  _infectious_disease             0 0 1 1
  _perception                     1 1 0 0
  _urbanization                   0 0 1 1
<<TermDocumentMatrix (terms: 5, documents: 2)>>
Non-/sparse entries: 5/5
Sparsity           : 50%
Maximal term length: 16
Weighting          : term frequency (tf)
```
```
                  Docs
Terms              1 2
  design           0 1
  dike             0 1
  flood_prevention 1 0
  learning_dike    1 0
  probability      0 1
<<TermDocumentMatrix (terms: 0, documents: 2)>>
Non-/sparse entries: 0/0
Sparsity           : 100%
Maximal term length: 0
Weighting          : term frequency (tf)

      Docs
Terms  1 2
<<TermDocumentMatrix (terms: 39, documents: 4)>>
Non-/sparse entries: 42/114
Sparsity           : 73%
Maximal term length: 31
Weighting          : term frequency (tf)
```
```
                                 Docs
Terms                             1 2 3 4
  _adaptación                     0 0 0 1
  _adaptation                     0 0 0 2
  _aléas_climatiques              1 0 0 0
  _cambio_climático               0 0 0 1
  _catastrophe                    1 0 0 0
  _changement_climatique          0 0 0 1
  changement_climatique           0 1 0 0
  _climate_and_hazards            1 0 0 0
  _climate_change                 0 1 0 1
  des                             0 0 1 0
  _enjeux                         1 0 0 0
  _flooding                       0 0 0 1
  _garona                         0 0 0 1
  _garonne                        0 0 0 1
  _gironde                        0 0 0 3
  inondation                      0 0 0 1
  _inundación                     0 0 0 1
  les                             0 0 1 0
  _modeling                       0 1 0 0
  _modélisation                   0 1 0 0
  _natural_disasters              1 0 0 0
  natural_risk                    1 0 0 0
  par                             0 0 1 0
  _plan_de_prévention_des_risques 0 1 0 0
  _prevención                     0 0 0 1
  _prevention                     1 0 0 1
  _prévention                     1 0 0 1
  _réglementation                 0 1 0 0
  _regulation                     0 1 0 0
  _risk_prevention_plan           0 1 0 0
  _risque_d'origine_naturelle     1 0 0 0
  _river_garonne                  0 0 0 1
  _stakes                         1 0 0 0
  _temps_forts                    1 0 0 0
  _vegetation                     0 1 0 0
  _végétation                     0 1 0 0
  _violent_weather                1 0 0 0
  _vulnérabilité                  1 0 0 0
  _vulnerability                  1 0 0 0
<<TermDocumentMatrix (terms: 3, documents: 4)>>
Non-/sparse entries: 6/6
Sparsity           : 50%
Maximal term length: 15
Weighting          : term frequency (tf)

                 Docs
Terms             1 2 3 4
  _climate_change 0 1 0 1
  _prevention     1 0 0 1
  _prévention     1 0 0 1
<<TermDocumentMatrix (terms: 3, documents: 3)>>
Non-/sparse entries: 9/0
Sparsity           : 0%
Maximal term length: 17
Weighting          : term frequency (tf)
```
```
                   Docs
Terms               1 2 3
  management_system 1 1 1
  waste_management  1 1 1
  waste_prevention  1 1 1
<<TermDocumentMatrix (terms: 3, documents: 3)>>
Non-/sparse entries: 9/0
Sparsity           : 0%
Maximal term length: 17
Weighting          : term frequency (tf)

                   Docs
Terms               1 2 3
  management_system 1 1 1
  waste_management  1 1 1
  waste_prevention  1 1 1
<<TermDocumentMatrix (terms: 4, documents: 2)>>
Non-/sparse entries: 4/4
Sparsity           : 50%
Maximal term length: 25
Weighting          : term frequency (tf)
```
```
                           Docs
Terms                       1 2
  america                   1 0
  climate_policy            1 0
  ge_environmental_sciences 0 1
  power_gap                 1 0
<<TermDocumentMatrix (terms: 0, documents: 2)>>
Non-/sparse entries: 0/0
Sparsity           : 100%
Maximal term length: 0
Weighting          : term frequency (tf)

      Docs
Terms  1 2
```

**Comment by chreman** [comment]
Sorry for the lengthy comment, I hope it serves the purposes. I tried implementing your suggestion, unfortunately if we filter at a cluster-group level, many keywords appear only once from one source paper, as can be seen in the TF-matrix for climate change prevention clusters (in the above list this refers to the first matrix of each group).
The second matrix shows the TF-matrix of a group, where the bound is raised to 2. not many keywords remain per group, sometimes leaving the group without naming.

**Comment by pkraker** [comment]
Thanks :)

**Pull request closed without merging**
