### PR TITLE
made stopwordsfilepath a parameter

### PR DESCRIPTION
**Pull request by chreman**
path to additional stopwords file now a parameter in vis_layout

### CODE REVIEW

**Comment by pkraker** [comment]
This change needs to be reflected in the main scripts in production and test.

**Comment by chreman** [comment]
@Bubblbu can you point me to the main scripts in production? only know about test

**Comment by Bubblbu** [comment]
Sry for backpedaling, but wouldn't it be nicer (and simpler) to use a flag for the the testing case?

**Comment by pkraker** [comment]
All path issues are currently handled in the main scripts and I think we should keep it that way. The approach has the added benefit that you can e.g. test different stop word lists using the evaluation framework.

**Comment by Bubblbu** [comment]
@chreman for production `other-scripts/text_similarity.R` calls vis_layout()

**Comment by Bubblbu** [comment]
@chreman had some time and added an implementation to PR #114 with commit 216feef

**Comment by chreman** [comment]
reflected it in production and test scripts, but still as a relative path.

**Comment by chreman** [comment]
closed after https://github.com/OpenKnowledgeMaps/Headstart/pull/114/commits/216feef9f2793fa235818949e48017be0d61ddcd

**Pull request closed without merging**
