### PR TITLE
issue 186 - trying a workaround for firefox iframe getComputedStyle bug

### PR DESCRIPTION
**Pull request by jaels**
It's a workaround I found online, but I can't test caus' I don't have this bug... maybe need to stage it so Chris can look

### CODE REVIEW

**Comment by chreman** [comment]
I'll try to test it locally

**Comment by chreman** [comment]
unfortunately no behaviour change locally, but we still can give it a try on staging

**Comment by jaels** [comment]
I'm guessing it won't work. Will try something else

**Comment by jaels** [comment]
Hey Chris,
I tried another fix.
It's a bug firefox has for years now, and it's still not fixed (it doesn't occur always) - https://bugzilla.mozilla.org/show_bug.cgi?id=548397
Very annoying... the workaround now is not very elegant, but please check if it's working.
Please also check if you have the bug in the image preview (change the preview_type to image in the config file) - I added a pdf file and preview to this PR. It's in the personal learning environment bubble.  

Let me know...
Cheers

**Comment by pkraker** [comment]
Closing this branch as it has been idle for some time now and conflicts with master.

**Pull request closed without merging**
