### PR TITLE
Linkedcat backend - multiword, phrase and negative keyword search

### PR DESCRIPTION
**Pull request by chreman**
This PR updates keyword searches: Multiple words, exact phrases, and negative keywords are now working as intended. Highlighting of more than one word now also works.

Please compare following maps/streamgraphs:
* Kaiser Leopold I
* "Kaiser Leopold I"
* Kaiser Leopold II
* "Kaiser Leopold II"
* Leopold -Kaiser -II
* hund
* hund wolf
* hund -wolf
* -hund wolf
* Ferdinand Wolf
* "Ferdinand Wolf" 
* "Ferdinand Wolf" Houdene
* "Ferdinand Wolf" -Houdene
* Ferdinand Wolf -Mundart
* Ferdinand Wolf Mundart

### CODE REVIEW

**Comment by pkraker** [comment]
Thanks! This certainly opens up the number of possible queries for LinkedCat. 

@tanteuschi and I did test larger number of queries, and we found the following issues:
* `die auf die Möglichkeit des Vorhandenseins von` works (both KM and SG, same results)
* `"die auf die Möglichkeit des Vorhandenseins von"`, which should return at least one paper from the query before fails for KM and SG.
* The queries `wien                    akademie   geschichte   ` and `wien                       -akademie              geschichte ` fail.
* The query `historisch-archäologischen` works, but the term is not highlighted in snippets.
* The query `wien akademie geschichte` works well, but when searching within the list for these three terms, only 80 document of the 528 documents are shown.
* Exclusions via `-` work well, but inclusions via `+` do not seem to work (e.g. `wien -akademie geschichte` works, `wien -akademie +geschichte` does not)
* `wien - akademie geschichte` has different results than `wien -akademie geschichte`

**Comment by chreman** [comment]
Thank you for the review and the additional examples. I added a few commits that fix nearly all of them. The only case where I did not achieve improvement is for

> The query wien akademie geschichte works well, but when searching within the list for these three terms, only 80 document of the 528 documents are shown.

I added a proximity factor to the query which in theory should demand that the query terms are no more than 7 tokens away from another. Unfortunately, it was not possible to retrieve highlights in this way where all tokens appear simultaneously. Highlighting of multi-word retrievals works in principal, as the examples of `"die auf die Möglichkeit des Vorhandenseins von"` and `die auf die Möglichkeit des Vorhandenseins von` demonstrate. But for the above case the document retrieval and highlighting produce incoherent results.

**Comment by pkraker** [comment]
Nice, this fixes most of the issues mentions. 

I only found problems for the following two queries:

* ` wien                                  -akademie + geschichte ` fails (note the white space at the beginning, between the words and at the end). Regarding the white spaces at the start and end, please also see #409 - may be worthwhile correcting this already in search.php and fixing another issue alongside this one.
* `wien -"akademie der wissenschaften"` produces a map that includes documents with the phrase "akademie der wissenschaften" (`wien +"akademie der wissenschaften"` and `wien "akademie der wissenschaften"` work well and produce the same output).

We'll move the highlighting issue to a different PR, as this issue also has a frontend component (documents are not correctly counted in the streamgraph it seems).

**Comment by chreman** [comment]
I added a commit that improves handling of negative keyword phrases. Additionally whitespace trimming of queries now happens early on as suggested in #409. This change has been tested on the other integrations as well, with the desired behavior.

**Comment by pkraker** [comment]
Thanks, I tested this, but still had problems with the following queries:

* `wien -"akademie der wissenschaften"` still includes documents, which contain the string "Akademie der Wissenschaften". It's the same btw for wien -"Akademie der Wissenschaften"
* Space before and after queries work well now, but multiple spaces between terms still fail. An example for this is (without inverted commas): "wien      -akademie               geschichte"

**Comment by chreman** [comment]
Thanks. I added a final commit that addresses multiple white spaces early on (search.php), and should improve behaviour on all integrations.
I propose to move the retrieval of documents which still contain excluded terms to another issue for now.

**Comment by pkraker** [comment]
Thanks, this works well now!

**Pull request merged**
